### ISSUE TITLE
Plugin does not support for Moodle v4.3+

### ISSUE THREAD

**Issue by AsheniPerera** [catalyst/moodle-local_aws#74] opened 2024-06-28 11:11 UTC
This plugin does not support for Moodle version 4.3+.
Giving the below error. 
The fixes have been done in master branch, but **still not have an official tag** for release.
**Can I know when you can provide a tag that supports for Moodle 4.3+ versions?**

Undefined constant GuzzleHttp\Client::VERSION
Backtrace:
* line 300 of /local/aws/sdk/Aws/functions.php: call to GuzzleHttp\default_user_agent()
* line 206 of /local/aws/sdk/Aws/Credentials/InstanceProfileProvider.php: call to Aws\default_user_agent()
* line 78 of /local/aws/sdk/Aws/Credentials/InstanceProfileProvider.php: call to Aws\Credentials\InstanceProfileProvider->request()
* line ? of unknownfile: call to Aws\Credentials\InstanceProfileProvider->Aws\Credentials\{closure}()
* line 71 of /lib/guzzlehttp/promises/src/Coroutine.php: call to Generator->current()
* line 86 of /lib/guzzlehttp/promises/src/Coroutine.php: call to GuzzleHttp\Promise\Coroutine->__construct()
* line 72 of /local/aws/sdk/Aws/Credentials/InstanceProfileProvider.php: call to GuzzleHttp\Promise\Coroutine::of()
* line 204 of /lib/guzzlehttp/promises/src/Promise.php: call to Aws\Credentials\InstanceProfileProvider->__invoke()
* line 169 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise::callHandler()
* line 42 of /lib/guzzlehttp/promises/src/RejectedPromise.php: call to GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
* line 48 of /lib/guzzlehttp/promises/src/TaskQueue.php: call to GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
* line 248 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\TaskQueue->run()
* line 224 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitFn()
* line 269 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
* line 226 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitList()
* line 62 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
* line 58 of /local/aws/sdk/Aws/AwsClientTrait.php: call to GuzzleHttp\Promise\Promise->wait()
* line 86 of /local/aws/sdk/Aws/AwsClientTrait.php: call to Aws\AwsClient->execute()

**Comment by danmarsden** [comment] 2024-06-30 04:07
@AsheniPerera do you mean Moodle 4.4? - or 4.3? - there is a published version in the plugins db for Moodle 4.3, but see #69 for details on 4.4 support.

If you have internal development capabilities, feel free to send us a PR with any improvements/bug fixes etc.

**Comment by danmarsden** [comment] 2024-06-30 04:10
looks like this was actually a duplicate of #56 which is fixed in github, closing this as a duplicate of that issue.

**Closed by danmarsden** 2024-06-30 04:10 UTC

**Comment by danmarsden** [comment] 2024-06-30 04:11
- note - we don't create tags or separate branches for each moodle release. see the readme file for information on the branch to use for different versions - in tihs case "master" supports 3.3 and higher.
